name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        toolchain: [stable, beta, nightly]
        include:
        - os: macos-11
          toolchain: stable
        - os: windows-2022
          toolchain: stable
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
        components: rustfmt, clippy
    - run: cargo build --verbose
    - run: cargo build --all-features --verbose
    - run: cargo test --verbose
    - run: cargo fmt --all -- --check
    - run: cargo clippy --all-targets -- -D warnings
    - run: cargo clippy --all-targets --all-features -- -D warnings
